[package]
name = "fireboard2mqtt"
version = "3.1.0"
edition = "2021"
publish = false

[features]
default = []
pretty_print_json_logs = []

[dependencies]
anyhow = "1.0.80"
tokio = { version = "1", features = ["full"] }
log = "0.4.21"
env_logger = "0.11.3"
url = "2.5.0"
serde = { version = "1.0", features = ["derive"]}
serde_json = { version = "1.0" }
rumqttc = "0.24.0"
bytes = "1.5"
memory-stats = "1.1.0"
human_bytes = { version = "0.4", default-features = false }
serde_repr = "0.1.18"
reqwest = { version = "0.12", default-features = false, features = ["default-tls", "charset", "macos-system-configuration", "json"] }
chrono = { version = "0.4.31", default-features = false, features = [
    "std",
    "serde",
    "clock"
]}
twelf = { version = "0.15.0", default-features = false, features = ["env", "default_trait"]}

[profile.dev]
debug = true
opt-level = 0
lto = "off"
panic = "unwind"
strip = false

[profile.release]
debug = 0
strip = true
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
